<?php
class ControllerExtensionModuleProbgServices extends Controller {
    private $error=array();
    public function index(){
        $this->load->language('extension/module/probg_services');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('setting/setting');$this->load->model('extension/module/probg_services');$this->model_extension_module_probg_services->ensureSchema();$this->load->model('user/user_group');if($this->user->hasPermission('modify','extension/module/probg_services')){foreach(array('extension/module/probg_services_block') as $route){$this->model_user_user_group->addPermission($this->user->getGroupId(),'access',$route);$this->model_user_user_group->addPermission($this->user->getGroupId(),'modify',$route);}}
        $this->load->model('extension/probg_services/category');$this->load->model('extension/probg_services/service');$this->load->model('extension/probg_services/enquiry');$this->load->model('localisation/language');$data['languages']=$this->model_localisation_language->getLanguages();
        if($this->request->server['REQUEST_METHOD']=='POST'&&$this->validate()){$post=$this->request->post;$post['module_probg_services_version']='1.5.0';$this->model_setting_setting->editSetting('module_probg_services',$post);$this->cache->delete('probg_services');$this->session->data['success']=$this->language->get('text_success');$this->response->redirect($this->url->link('extension/module/probg_services','user_token='.$this->session->data['user_token'],true));}
        $data['error_warning']=$this->error['warning']??'';$data['error_limit']=$this->error['limit']??'';$data['error_security']=$this->error['security']??'';$data['success']=$this->session->data['success']??'';unset($this->session->data['success']);$token='user_token='.$this->session->data['user_token'];
        $data['breadcrumbs']=array(array('text'=>$this->language->get('text_home'),'href'=>$this->url->link('common/dashboard',$token,true)),array('text'=>$this->language->get('text_extension'),'href'=>$this->url->link('marketplace/extension',$token.'&type=module',true)),array('text'=>$this->language->get('heading_title'),'href'=>$this->url->link('extension/module/probg_services',$token,true)));
        $data['action']=$this->url->link('extension/module/probg_services',$token,true);$data['settings_url']=$data['action'];$data['categories_url']=$this->url->link('extension/probg_services/category',$token,true);$data['services_url']=$this->url->link('extension/probg_services/service',$token,true);$data['enquiries_url']=$this->url->link('extension/probg_services/enquiry',$token,true);$data['retention_url']=$this->url->link('extension/probg_services/enquiry/retention',$token,true);$data['cancel']=$this->url->link('marketplace/extension',$token.'&type=module',true);$data['total_categories']=$this->model_extension_probg_services_category->getTotalCategories();$data['total_services']=$this->model_extension_probg_services_service->getTotalServices();$data['total_enquiries']=$this->model_extension_probg_services_enquiry->getTotalEnquiries();
        $defaults=array('module_probg_services_status'=>0,'module_probg_services_limit'=>12,'module_probg_services_cache_status'=>1,'module_probg_services_sitemap'=>1,'module_probg_services_provider_name'=>'','module_probg_services_provider_url'=>'','module_probg_services_provider_logo'=>'','module_probg_services_sitemap_changefreq'=>'weekly','module_probg_services_sitemap_priority_section'=>'0.8','module_probg_services_sitemap_priority_category'=>'0.7','module_probg_services_sitemap_priority_service'=>'0.8','module_probg_services_rate_limit_count'=>5,'module_probg_services_rate_limit_minutes'=>60,'module_probg_services_upload_max_files'=>5,'module_probg_services_upload_max_mb'=>5,'module_probg_services_upload_extensions'=>'pdf,doc,docx,xls,xlsx,jpg,jpeg,png,webp,txt','module_probg_services_retention_days'=>730);foreach($defaults as $field=>$default){if(isset($this->request->post[$field]))$data[$field]=$this->request->post[$field];else{$value=$this->config->get($field);$data[$field]=$value!==null?$value:$default;}}
        $data['module_probg_services_description']=$this->request->post['module_probg_services_description']??((array)$this->config->get('module_probg_services_description'));
        $data['version']='1.5.0';$data['stage']='10';$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/module/probg_services',$data));
    }
    public function install(){$this->load->model('extension/module/probg_services');$this->model_extension_module_probg_services->install();$this->load->model('user/user_group');foreach(array('extension/module/probg_services','extension/module/probg_services_block','extension/probg_services/category','extension/probg_services/service','extension/probg_services/enquiry') as $route){$this->model_user_user_group->addPermission($this->user->getGroupId(),'access',$route);$this->model_user_user_group->addPermission($this->user->getGroupId(),'modify',$route);}}
    public function uninstall(){$this->load->model('extension/module/probg_services');$this->model_extension_module_probg_services->uninstall();$this->load->model('setting/setting');$this->model_setting_setting->deleteSetting('module_probg_services');}
    protected function validate(){if(!$this->user->hasPermission('modify','extension/module/probg_services'))$this->error['warning']=$this->language->get('error_permission');$limit=(int)($this->request->post['module_probg_services_limit']??0);if($limit<1||$limit>100)$this->error['limit']=$this->language->get('error_limit');$count=(int)($this->request->post['module_probg_services_rate_limit_count']??0);$minutes=(int)($this->request->post['module_probg_services_rate_limit_minutes']??0);$files=(int)($this->request->post['module_probg_services_upload_max_files']??0);$mb=(int)($this->request->post['module_probg_services_upload_max_mb']??0);$days=(int)($this->request->post['module_probg_services_retention_days']??0);if($count<1||$count>100||$minutes<1||$minutes>1440||$files<0||$files>10||$mb<1||$mb>25||$days<1)$this->error['security']=$this->language->get('error_security');return !$this->error;}
}
