<?php
class ModelExtensionProbgServicesEnquiry extends Model {
    public function getEnquiries($data=array()){$language_id=(int)$this->config->get('config_language_id');$sql="SELECT e.*,sd.name AS service_name,CONCAT(u.firstname,' ',u.lastname) AS assigned_user FROM `".DB_PREFIX."probg_service_enquiry` e LEFT JOIN `".DB_PREFIX."probg_service_description` sd ON(sd.service_id=e.service_id AND sd.language_id='".$language_id."') LEFT JOIN `".DB_PREFIX."user` u ON(u.user_id=e.assigned_user_id) WHERE 1";if(!empty($data['filter_name']))$sql.=" AND e.name LIKE '%".$this->db->escape($data['filter_name'])."%'";if(!empty($data['filter_email']))$sql.=" AND e.email LIKE '%".$this->db->escape($data['filter_email'])."%'";if(!empty($data['filter_service_id']))$sql.=" AND e.service_id='".(int)$data['filter_service_id']."'";if(isset($data['filter_status_id'])&&$data['filter_status_id']!=='')$sql.=" AND e.status_id='".(int)$data['filter_status_id']."'";if(isset($data['filter_assigned_user_id'])&&$data['filter_assigned_user_id']!=='')$sql.=" AND e.assigned_user_id='".(int)$data['filter_assigned_user_id']."'";if(!empty($data['filter_date_from']))$sql.=" AND DATE(e.date_added)>='".$this->db->escape($data['filter_date_from'])."'";if(!empty($data['filter_date_to']))$sql.=" AND DATE(e.date_added)<='".$this->db->escape($data['filter_date_to'])."'";$sql.=" ORDER BY e.date_added DESC,e.enquiry_id DESC";$start=max(0,(int)($data['start']??0));$limit=max(1,(int)($data['limit']??20));$sql.=" LIMIT ".$start.",".$limit;return $this->db->query($sql)->rows;}
    public function getTotalEnquiries($data=array()){$sql="SELECT COUNT(*) AS total FROM `".DB_PREFIX."probg_service_enquiry` e WHERE 1";if(!empty($data['filter_name']))$sql.=" AND e.name LIKE '%".$this->db->escape($data['filter_name'])."%'";if(!empty($data['filter_email']))$sql.=" AND e.email LIKE '%".$this->db->escape($data['filter_email'])."%'";if(!empty($data['filter_service_id']))$sql.=" AND e.service_id='".(int)$data['filter_service_id']."'";if(isset($data['filter_status_id'])&&$data['filter_status_id']!=='')$sql.=" AND e.status_id='".(int)$data['filter_status_id']."'";if(isset($data['filter_assigned_user_id'])&&$data['filter_assigned_user_id']!=='')$sql.=" AND e.assigned_user_id='".(int)$data['filter_assigned_user_id']."'";if(!empty($data['filter_date_from']))$sql.=" AND DATE(e.date_added)>='".$this->db->escape($data['filter_date_from'])."'";if(!empty($data['filter_date_to']))$sql.=" AND DATE(e.date_added)<='".$this->db->escape($data['filter_date_to'])."'";return (int)$this->db->query($sql)->row['total'];}
    public function getEnquiry($id){$l=(int)$this->config->get('config_language_id');return $this->db->query("SELECT e.*,sd.name AS service_name,CONCAT(u.firstname,' ',u.lastname) AS assigned_user FROM `".DB_PREFIX."probg_service_enquiry` e LEFT JOIN `".DB_PREFIX."probg_service_description` sd ON(sd.service_id=e.service_id AND sd.language_id='".$l."') LEFT JOIN `".DB_PREFIX."user` u ON(u.user_id=e.assigned_user_id) WHERE e.enquiry_id='".(int)$id."'")->row;}
    public function getFile($file_id){return $this->db->query("SELECT * FROM `".DB_PREFIX."probg_service_enquiry_file` WHERE enquiry_file_id='".(int)$file_id."'")->row;}
    public function getFiles($id){return $this->db->query("SELECT * FROM `".DB_PREFIX."probg_service_enquiry_file` WHERE enquiry_id='".(int)$id."' ORDER BY enquiry_file_id ASC")->rows;}
    public function getHistory($id){return $this->db->query("SELECT h.*,CONCAT(u.firstname,' ',u.lastname) AS user_name FROM `".DB_PREFIX."probg_service_enquiry_history` h LEFT JOIN `".DB_PREFIX."user` u ON(u.user_id=h.user_id) WHERE h.enquiry_id='".(int)$id."' ORDER BY h.date_added DESC,h.enquiry_history_id DESC")->rows;}
    public function getUsers(){return $this->db->query("SELECT user_id,username,firstname,lastname FROM `".DB_PREFIX."user` WHERE status='1' ORDER BY firstname,lastname,username")->rows;}
    public function updateAssignment($id,$user_id){$this->db->query("UPDATE `".DB_PREFIX."probg_service_enquiry` SET assigned_user_id='".(int)$user_id."',date_modified=NOW() WHERE enquiry_id='".(int)$id."'");}
    public function addHistory($id,$status_id,$comment,$user_id,$notify=0){$this->db->query("UPDATE `".DB_PREFIX."probg_service_enquiry` SET status_id='".(int)$status_id."',date_modified=NOW() WHERE enquiry_id='".(int)$id."'");$this->db->query("INSERT INTO `".DB_PREFIX."probg_service_enquiry_history` SET enquiry_id='".(int)$id."',status_id='".(int)$status_id."',user_id='".(int)$user_id."',comment='".$this->db->escape($comment)."',notify='".(int)$notify."',date_added=NOW()");}
    public function anonymizeEnquiry($id){$this->db->query("UPDATE `".DB_PREFIX."probg_service_enquiry` SET customer_id=0,name='Anonymized',email='',telephone='',company='',website='',subject='',message='',budget='',desired_deadline='',ip='',user_agent='',date_modified=NOW() WHERE enquiry_id='".(int)$id."'");foreach($this->getFiles($id) as $f)$this->deletePhysicalFile($f['filename']);$this->db->query("DELETE FROM `".DB_PREFIX."probg_service_enquiry_file` WHERE enquiry_id='".(int)$id."'");$this->addHistory($id,(int)$this->getEnquiry($id)['status_id'],'Personal data anonymized.',$this->user->getId(),0);}
    public function anonymizeOlderThan($days){$days=max(1,(int)$days);$rows=$this->db->query("SELECT enquiry_id FROM `".DB_PREFIX."probg_service_enquiry` WHERE name<>'Anonymized' AND date_added<DATE_SUB(NOW(),INTERVAL ".$days." DAY)")->rows;foreach($rows as $r)$this->anonymizeEnquiry((int)$r['enquiry_id']);return count($rows);}
    public function deleteEnquiry($id){foreach($this->getFiles($id) as $f)$this->deletePhysicalFile($f['filename']);$this->db->query("DELETE FROM `".DB_PREFIX."probg_service_enquiry_history` WHERE enquiry_id='".(int)$id."'");$this->db->query("DELETE FROM `".DB_PREFIX."probg_service_enquiry_file` WHERE enquiry_id='".(int)$id."'");$this->db->query("DELETE FROM `".DB_PREFIX."probg_service_enquiry` WHERE enquiry_id='".(int)$id."'");}
    private function deletePhysicalFile($filename){$path=DIR_STORAGE.'upload/'.basename($filename);if(is_file($path))@unlink($path);}
}
