<?php
class ModelExtensionProbgServicesService extends Model {
    public function addService($data) {
        $this->db->query("INSERT INTO " . DB_PREFIX . "probg_service SET category_id='" . (int)$data['category_id'] . "', image='" . $this->db->escape($data['image']) . "', social_image='" . $this->db->escape($data['social_image']) . "', price='" . (float)$data['price'] . "', show_price='" . (int)$data['show_price'] . "', enquiry_status='" . (int)$data['enquiry_status'] . "', sort_order='" . (int)$data['sort_order'] . "', status='" . (int)$data['status'] . "', date_available=" . (!empty($data['date_available']) ? "'" . $this->db->escape($data['date_available']) . "'" : "NULL") . ", date_added=NOW(), date_modified=NOW()");
        $service_id = $this->db->getLastId();
        $this->saveDescriptions($service_id, $data); $this->saveStores($service_id, $data); $this->saveImages($service_id, $data); $this->saveRelated($service_id, $data); $this->saveSeoUrls($service_id, $data);
        return $service_id;
    }
    public function editService($service_id, $data) {
        $this->db->query("UPDATE " . DB_PREFIX . "probg_service SET category_id='" . (int)$data['category_id'] . "', image='" . $this->db->escape($data['image']) . "', social_image='" . $this->db->escape($data['social_image']) . "', price='" . (float)$data['price'] . "', show_price='" . (int)$data['show_price'] . "', enquiry_status='" . (int)$data['enquiry_status'] . "', sort_order='" . (int)$data['sort_order'] . "', status='" . (int)$data['status'] . "', date_available=" . (!empty($data['date_available']) ? "'" . $this->db->escape($data['date_available']) . "'" : "NULL") . ", date_modified=NOW() WHERE service_id='" . (int)$service_id . "'");
        foreach (array('probg_service_description','probg_service_to_store','probg_service_image','probg_service_related') as $table) $this->db->query("DELETE FROM " . DB_PREFIX . $table . " WHERE service_id='" . (int)$service_id . "'");
        $this->deleteSeoUrls($service_id); $this->saveDescriptions($service_id,$data); $this->saveStores($service_id,$data); $this->saveImages($service_id,$data); $this->saveRelated($service_id,$data); $this->saveSeoUrls($service_id,$data);
    }
    public function deleteService($service_id) {
        foreach (array('probg_service','probg_service_description','probg_service_to_store','probg_service_image','probg_service_related') as $table) $this->db->query("DELETE FROM " . DB_PREFIX . $table . " WHERE service_id='" . (int)$service_id . "'");
        $this->db->query("DELETE FROM " . DB_PREFIX . "probg_service_related WHERE related_id='" . (int)$service_id . "'"); $this->deleteSeoUrls($service_id);
    }
    public function getService($service_id) { return $this->db->query("SELECT s.*,sd.name FROM " . DB_PREFIX . "probg_service s LEFT JOIN " . DB_PREFIX . "probg_service_description sd ON(s.service_id=sd.service_id AND sd.language_id='".(int)$this->config->get('config_language_id')."') WHERE s.service_id='".(int)$service_id."'")->row; }
    public function getServices($data=array()) {
        $sql="SELECT s.*,sd.name,cd.name AS category_name FROM ".DB_PREFIX."probg_service s LEFT JOIN ".DB_PREFIX."probg_service_description sd ON(s.service_id=sd.service_id AND sd.language_id='".(int)$this->config->get('config_language_id')."') LEFT JOIN ".DB_PREFIX."probg_service_category_description cd ON(s.category_id=cd.category_id AND cd.language_id='".(int)$this->config->get('config_language_id')."') WHERE 1";
        if(!empty($data['filter_name']))$sql.=" AND sd.name LIKE '%".$this->db->escape($data['filter_name'])."%'"; if(isset($data['filter_category_id'])&&$data['filter_category_id']!=='')$sql.=" AND s.category_id='".(int)$data['filter_category_id']."'"; if(isset($data['filter_status'])&&$data['filter_status']!=='')$sql.=" AND s.status='".(int)$data['filter_status']."'";
        $sort_data=array('sd.name','cd.name','s.price','s.sort_order','s.status','s.date_added'); $sort=isset($data['sort'])&&in_array($data['sort'],$sort_data,true)?$data['sort']:'s.sort_order'; $order=isset($data['order'])&&$data['order']==='DESC'?'DESC':'ASC'; $sql.=" ORDER BY $sort $order, sd.name ASC";
        if(isset($data['start'])||isset($data['limit'])){$start=max(0,(int)($data['start']??0));$limit=max(1,(int)($data['limit']??20));$sql.=" LIMIT $start,$limit";} return $this->db->query($sql)->rows;
    }
    public function getTotalServices($data=array()) { $sql="SELECT COUNT(*) AS total FROM ".DB_PREFIX."probg_service s LEFT JOIN ".DB_PREFIX."probg_service_description sd ON(s.service_id=sd.service_id AND sd.language_id='".(int)$this->config->get('config_language_id')."') WHERE 1"; if(!empty($data['filter_name']))$sql.=" AND sd.name LIKE '%".$this->db->escape($data['filter_name'])."%'"; if(isset($data['filter_category_id'])&&$data['filter_category_id']!=='')$sql.=" AND s.category_id='".(int)$data['filter_category_id']."'"; if(isset($data['filter_status'])&&$data['filter_status']!=='')$sql.=" AND s.status='".(int)$data['filter_status']."'"; return (int)$this->db->query($sql)->row['total']; }
    public function getServiceDescriptions($service_id){$data=array();foreach($this->db->query("SELECT * FROM ".DB_PREFIX."probg_service_description WHERE service_id='".(int)$service_id."'")->rows as $row)$data[$row['language_id']]=$row;return $data;}
    public function getServiceStores($service_id){return array_column($this->db->query("SELECT store_id FROM ".DB_PREFIX."probg_service_to_store WHERE service_id='".(int)$service_id."'")->rows,'store_id');}
    public function getServiceImages($service_id){return $this->db->query("SELECT * FROM ".DB_PREFIX."probg_service_image WHERE service_id='".(int)$service_id."' ORDER BY sort_order ASC, service_image_id ASC")->rows;}
    public function getServiceRelated($service_id){return array_column($this->db->query("SELECT related_id FROM ".DB_PREFIX."probg_service_related WHERE service_id='".(int)$service_id."'")->rows,'related_id');}
    public function getServiceSeoUrls($service_id){$data=array();foreach($this->db->query("SELECT store_id,language_id,keyword FROM ".DB_PREFIX."seo_url WHERE query='extension/probg_services/service&service_id=".(int)$service_id."'")->rows as $row)$data[$row['store_id']][$row['language_id']]=$row['keyword'];return $data;}
    public function getSeoUrlByKeyword($keyword,$store_id,$language_id){return $this->db->query("SELECT seo_url_id,query FROM ".DB_PREFIX."seo_url WHERE keyword='".$this->db->escape($keyword)."' AND store_id='".(int)$store_id."' AND language_id='".(int)$language_id."' LIMIT 1")->row;}
    private function saveDescriptions($service_id,$data){foreach($data['service_description'] as $language_id=>$value){$meta_title=trim($value['meta_title'])!==''?$value['meta_title']:$value['name'];$this->db->query("INSERT INTO ".DB_PREFIX."probg_service_description SET service_id='".(int)$service_id."',language_id='".(int)$language_id."',name='".$this->db->escape($value['name'])."',subtitle='".$this->db->escape($value['subtitle'])."',description_short='".$this->db->escape($value['description_short'])."',description='".$this->db->escape($value['description'])."',price_text='".$this->db->escape($value['price_text'])."',button_text='".$this->db->escape($value['button_text'])."',meta_title='".$this->db->escape($meta_title)."',meta_description='".$this->db->escape($value['meta_description'])."',meta_keyword='".$this->db->escape($value['meta_keyword'])."'");}}
    private function saveStores($service_id,$data){foreach(($data['service_store']??array(0)) as $store_id)$this->db->query("INSERT INTO ".DB_PREFIX."probg_service_to_store SET service_id='".(int)$service_id."',store_id='".(int)$store_id."'");}
    private function saveImages($service_id,$data){foreach(($data['service_image']??array()) as $image){if(!empty($image['image']))$this->db->query("INSERT INTO ".DB_PREFIX."probg_service_image SET service_id='".(int)$service_id."',image='".$this->db->escape($image['image'])."',sort_order='".(int)$image['sort_order']."'");}}
    private function saveRelated($service_id,$data){foreach(($data['service_related']??array()) as $related_id)if((int)$related_id!==$service_id)$this->db->query("INSERT IGNORE INTO ".DB_PREFIX."probg_service_related SET service_id='".(int)$service_id."',related_id='".(int)$related_id."'");}
    private function saveSeoUrls($service_id,$data){$stores=$data['service_store']??array(0);foreach($stores as $store_id)foreach($data['service_description'] as $language_id=>$description){$keyword=trim($data['service_seo_url'][$store_id][$language_id]??'');if($keyword==='')$keyword=$this->uniqueSlug($service_id.'-'.$this->slugify($description['name']),$store_id,$language_id,$service_id);if($keyword!=='')$this->db->query("INSERT INTO ".DB_PREFIX."seo_url SET store_id='".(int)$store_id."',language_id='".(int)$language_id."',query='extension/probg_services/service&service_id=".(int)$service_id."',keyword='".$this->db->escape($keyword)."'");}}
    private function deleteSeoUrls($service_id){$this->db->query("DELETE FROM ".DB_PREFIX."seo_url WHERE query='extension/probg_services/service&service_id=".(int)$service_id."'");}
    private function uniqueSlug($slug,$store_id,$language_id,$service_id){if($slug==='')$slug=$service_id.'-service';$base=$slug;$i=2;while(true){$row=$this->getSeoUrlByKeyword($slug,$store_id,$language_id);if(!$row||$row['query']==='extension/probg_services/service&service_id='.(int)$service_id)return $slug;$slug=$base.'-'.$i++;}}
    private function slugify($value){$map=array('а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','ж'=>'zh','з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'h','ц'=>'ts','ч'=>'ch','ш'=>'sh','щ'=>'sht','ъ'=>'a','ь'=>'','ю'=>'yu','я'=>'ya');$value=utf8_strtolower(trim($value));$value=strtr($value,$map);$value=preg_replace('/[^a-z0-9]+/u','-',$value);return trim($value,'-');}
}
