<?php
class ControllerExtensionProbgServicesService extends Controller {
    private $error=array();
    public function index(){$this->load->language('extension/probg_services/service');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('extension/probg_services/service');$this->getList();}
    public function add(){$this->load->language('extension/probg_services/service');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('extension/probg_services/service');if($this->request->server['REQUEST_METHOD']=='POST'&&$this->validateForm()){$this->model_extension_probg_services_service->addService($this->request->post);$this->session->data['success']=$this->language->get('text_success');$this->response->redirect($this->url->link('extension/probg_services/service','user_token='.$this->session->data['user_token'],true));}$this->getForm();}
    public function edit(){$this->load->language('extension/probg_services/service');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('extension/probg_services/service');if($this->request->server['REQUEST_METHOD']=='POST'&&$this->validateForm()){$this->model_extension_probg_services_service->editService((int)$this->request->get['service_id'],$this->request->post);$this->session->data['success']=$this->language->get('text_success');$this->response->redirect($this->url->link('extension/probg_services/service','user_token='.$this->session->data['user_token'],true));}$this->getForm();}
    public function delete(){$this->load->language('extension/probg_services/service');$this->load->model('extension/probg_services/service');if(isset($this->request->post['selected'])&&$this->validateDelete()){foreach($this->request->post['selected'] as $service_id)$this->model_extension_probg_services_service->deleteService((int)$service_id);$this->session->data['success']=$this->language->get('text_success_delete');}$this->response->redirect($this->url->link('extension/probg_services/service','user_token='.$this->session->data['user_token'],true));}
    protected function getList(){
        $filter_name=$this->request->get['filter_name']??'';$filter_category_id=$this->request->get['filter_category_id']??'';$filter_status=$this->request->get['filter_status']??'';$page=max(1,(int)($this->request->get['page']??1));$limit=(int)$this->config->get('config_limit_admin');
        $filter_data=array('filter_name'=>$filter_name,'filter_category_id'=>$filter_category_id,'filter_status'=>$filter_status,'start'=>($page-1)*$limit,'limit'=>$limit);$total=$this->model_extension_probg_services_service->getTotalServices($filter_data);$data['services']=array();foreach($this->model_extension_probg_services_service->getServices($filter_data) as $r)$data['services'][]=array('service_id'=>$r['service_id'],'name'=>$r['name'],'category_name'=>$r['category_name'],'price'=>$this->currency->format($r['price'],$this->config->get('config_currency')),'show_price'=>$r['show_price'],'status'=>$r['status'],'sort_order'=>$r['sort_order'],'edit'=>$this->url->link('extension/probg_services/service/edit','user_token='.$this->session->data['user_token'].'&service_id='.$r['service_id'],true));
        $this->load->model('extension/probg_services/category');$data['categories']=$this->model_extension_probg_services_category->getCategories(array('sort'=>'cd.name','order'=>'ASC'));$data['filter_name']=$filter_name;$data['filter_category_id']=$filter_category_id;$data['filter_status']=$filter_status;$data['user_token']=$this->session->data['user_token'];$data['add']=$this->url->link('extension/probg_services/service/add','user_token='.$data['user_token'],true);$data['delete']=$this->url->link('extension/probg_services/service/delete','user_token='.$data['user_token'],true);$data['error_warning']=$this->error['warning']??'';$data['success']=$this->session->data['success']??'';unset($this->session->data['success']);$this->navigation($data);
        $data['breadcrumbs']=array(array('text'=>$this->language->get('text_home'),'href'=>$this->url->link('common/dashboard','user_token='.$data['user_token'],true)),array('text'=>'ProBG Services','href'=>$data['settings_url']),array('text'=>$this->language->get('heading_title'),'href'=>$data['services_url']));$pagination=new Pagination();$pagination->total=$total;$pagination->page=$page;$pagination->limit=$limit;$pagination->url=$this->url->link('extension/probg_services/service','user_token='.$data['user_token'].'&page={page}',true);$data['pagination']=$pagination->render();$data['results']=sprintf($this->language->get('text_pagination'),$total?(($page-1)*$limit)+1:0,min($total,$page*$limit),$total,ceil($total/$limit));$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/probg_services/service_list',$data));
    }
    protected function getForm(){
        $service_id=(int)($this->request->get['service_id']??0);$info=$service_id?$this->model_extension_probg_services_service->getService($service_id):array();$data['text_form']=$service_id?$this->language->get('text_edit'):$this->language->get('text_add');$data['error_warning']=$this->error['warning']??'';$data['error_name']=$this->error['name']??array();$data['error_keyword']=$this->error['keyword']??array();$data['user_token']=$this->session->data['user_token'];$data['action']=$service_id?$this->url->link('extension/probg_services/service/edit','user_token='.$data['user_token'].'&service_id='.$service_id,true):$this->url->link('extension/probg_services/service/add','user_token='.$data['user_token'],true);$data['cancel']=$this->url->link('extension/probg_services/service','user_token='.$data['user_token'],true);$this->navigation($data);
        $this->load->model('localisation/language');$data['languages']=$this->model_localisation_language->getLanguages();$this->load->model('setting/store');$data['stores']=$this->model_setting_store->getStores();$this->load->model('extension/probg_services/category');$data['categories']=$this->model_extension_probg_services_category->getCategories(array('sort'=>'cd.name','order'=>'ASC'));$this->load->model('catalog/product');$this->load->model('tool/image');$defaults=array('category_id'=>0,'image'=>'','social_image'=>'','price'=>'0.0000','show_price'=>0,'enquiry_status'=>1,'sort_order'=>0,'status'=>1,'date_available'=>date('Y-m-d'));foreach($defaults as $f=>$d)$data[$f]=$this->request->post[$f]??($info[$f]??$d);
        $data['service_description']=$this->request->post['service_description']??($service_id?$this->model_extension_probg_services_service->getServiceDescriptions($service_id):array());$data['service_store']=$this->request->post['service_store']??($service_id?$this->model_extension_probg_services_service->getServiceStores($service_id):array(0));$data['service_image']=$this->request->post['service_image']??($service_id?$this->model_extension_probg_services_service->getServiceImages($service_id):array());$data['service_related']=$this->request->post['service_related']??($service_id?$this->model_extension_probg_services_service->getServiceRelated($service_id):array());$data['service_product']=$this->request->post['service_product']??($service_id?$this->model_extension_probg_services_service->getServiceProducts($service_id):array());$data['service_seo_url']=$this->request->post['service_seo_url']??($service_id?$this->model_extension_probg_services_service->getServiceSeoUrls($service_id):array());$data['related_services']=array();foreach($data['service_related'] as $related_id){$r=$this->model_extension_probg_services_service->getService($related_id);if($r)$data['related_services'][]=$r;}$data['recommended_products']=array();foreach($data['service_product'] as $row){$product_id=is_array($row)?(int)$row['product_id']:(int)$row;$sort_order=is_array($row)?(int)($row['sort_order']??0):0;$product=$this->model_catalog_product->getProduct($product_id);if($product)$data['recommended_products'][]=array('product_id'=>$product_id,'name'=>$product['name'],'sort_order'=>$sort_order);}
        $data['thumb']=$data['image']&&is_file(DIR_IMAGE.$data['image'])?$this->model_tool_image->resize($data['image'],100,100):$this->model_tool_image->resize('no_image.png',100,100);$data['social_thumb']=$data['social_image']&&is_file(DIR_IMAGE.$data['social_image'])?$this->model_tool_image->resize($data['social_image'],100,100):$this->model_tool_image->resize('no_image.png',100,100);$data['placeholder']=$this->model_tool_image->resize('no_image.png',100,100);foreach($data['service_image'] as &$image)$image['thumb']=$image['image']&&is_file(DIR_IMAGE.$image['image'])?$this->model_tool_image->resize($image['image'],100,100):$data['placeholder'];unset($image);$data['breadcrumbs']=array(array('text'=>$this->language->get('text_home'),'href'=>$this->url->link('common/dashboard','user_token='.$data['user_token'],true)),array('text'=>'ProBG Services','href'=>$data['settings_url']),array('text'=>$this->language->get('heading_title'),'href'=>$data['services_url']));$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/probg_services/service_form',$data));
    }
    private function navigation(&$data){$token='user_token='.$this->session->data['user_token'];$data['settings_url']=$this->url->link('extension/module/probg_services',$token,true);$data['categories_url']=$this->url->link('extension/probg_services/category',$token,true);$data['services_url']=$this->url->link('extension/probg_services/service',$token,true);$data['enquiries_url']=$this->url->link('extension/probg_services/enquiry',$token,true);}
    public function autocomplete(){$json=array();if(isset($this->request->get['filter_name'])){$this->load->model('extension/probg_services/service');foreach($this->model_extension_probg_services_service->getServices(array('filter_name'=>$this->request->get['filter_name'],'start'=>0,'limit'=>10)) as $r)$json[]=array('service_id'=>$r['service_id'],'name'=>strip_tags(html_entity_decode($r['name'],ENT_QUOTES,'UTF-8')));}$this->response->addHeader('Content-Type: application/json');$this->response->setOutput(json_encode($json));}
    protected function validateForm(){if(!$this->user->hasPermission('modify','extension/probg_services/service'))$this->error['warning']=$this->language->get('error_permission');foreach(($this->request->post['service_description']??array()) as $language_id=>$v)if(utf8_strlen(trim($v['name']))<1||utf8_strlen($v['name'])>255)$this->error['name'][$language_id]=$this->language->get('error_name');foreach(($this->request->post['service_seo_url']??array()) as $store_id=>$langs)foreach($langs as $language_id=>$keyword)if(trim($keyword)!==''){$found=$this->model_extension_probg_services_service->getSeoUrlByKeyword(trim($keyword),$store_id,$language_id);$expected='extension/probg_services/service&service_id='.(int)($this->request->get['service_id']??0);if($found&&$found['query']!==$expected)$this->error['keyword'][$store_id][$language_id]=$this->language->get('error_keyword');}return !$this->error;}
    protected function validateDelete(){if(!$this->user->hasPermission('modify','extension/probg_services/service'))$this->error['warning']=$this->language->get('error_permission');return !$this->error;}
}
